name: Build

on:
  push:
    branches: dev

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: true
          tags: testuigolos/updater:latest
